name: Main workflow
on:
  push:
    branches:
      - "master"
jobs:
  perl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        perl: ["5.8", "5.12", "5.30", "5.34", "5.32", "5.30"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: prove -lv t
